frontend deploy test

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -14,16 +14,16 @@ RUN flutter doctor
 # Install Dart
 RUN apt-get update && apt-get install -y apt-transport-https gnupg
 RUN wget -q https://dl-ssl.google.com/linux/linux_signing_key.pub -O dart.key
-RUN gpg --dearmor dart.key | tee /etc/apt/trusted.gpg.d/dart.gpg > /dev/null
-RUN retry_wget() { \
-  wget --no-check-certificate -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian_stable/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list || \
-  if [ $retries -gt 0 ]; then \
-    echo "Download failed, retrying..." && retries=$((retries-1)) && sleep 1 && retry_wget; \
-  else \
-    echo "Download failed after multiple retries." && exit 1; \
-  fi \
-} \
-retries=3; retry_wget
+RUN gpg --dearmor dart.key | tee /etc/apt/trusted.gpg.d/dart.gpg > /dev/null && \
+  retry_wget() { \
+    wget --no-check-certificate -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian_stable/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list || \
+    if [ $retries -gt 0 ]; then \
+      echo "Download failed, retrying..." && retries=$((retries-1)) && sleep 1 && retry_wget; \
+    else \
+      echo "Download failed after multiple retries." && exit 1; \
+    fi \
+  }; \
+  retries=3; retry_wget
 RUN apt-get update && apt-get install -y dart
 
 # Set working directory
